name: Puppeteer E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Puppeteer script
        env:
          DISPLAY: ':99.0'
        run: node navigate-and-capture.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: puppeteer-artifacts
          path: artifacts/**
