name: Puppeteer E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          echo "🔍 Checking for package-lock.json…"
          if [ -f package-lock.json ]; then
            echo "❇️  package-lock.json found, running npm ci"
            npm ci
          else
            echo "⚠️  No lockfile found, running npm install"
            npm install
          fi

      - name: Ensure Puppeteer is installed
        run: npm install --no-save puppeteer

      - name: Run Puppeteer script
        env:
          DISPLAY: ':99.0'
        run: node navigate-and-capture.js

      - name: Upload Puppeteer artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: puppeteer-artifacts
          path: artifacts/**
