# .github/workflows/signup.yml
# GitHub Actions workflow to run the Puppeteer signup script against a real browser

name: Gmail Signup CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  signup-flow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install puppeteer-real-browser

    - name: Launch Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run signup script
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      run: |
        node navigate-signup-full-real.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: signup-artifacts
        path: artifacts/**
